// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nftnvpcugbknbtxhnhfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdG52cGN1Z2JrbmJ0eGhuaGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjgxNTksImV4cCI6MjA2MTcwNDE1OX0.yJCwm8cObrOmL2ZY9m9EpinUJWv8gBpLvuL7ipuAqtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);